services:
  postgres_audit:
    build: .
    container_name: postgres_perf
    command: postgres -c shared_preload_libraries=pgaudit
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data-audit:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"


volumes:
  postgres-data-audit: